# Changes here will be overwritten by Copier
_commit: 0.3.3
_src_path: gh:pdm-project/copier-pdm
author_email: mianghong@gmail.com
author_fullname: Frost Ming
author_username: frostming
build_doc: true
copyright_date: '2022'
copyright_holder: Frost Ming
copyright_holder_email: mianghong@gmail.com
copyright_license: MIT
project_description: Python monorepo made easy
project_name: monas
python_package_distribution_name: monas
python_package_import_name: monas
python_package_requires_python: '>=3.7'
repository_name: monas
repository_namespace: frostming
